# Generated by Django 3.1.2 on 2021-03-01 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='product_imgs')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('pt_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='耳机类型编号')),
                ('pt_name', models.CharField(max_length=200, verbose_name='耳机类型名称')),
                ('pt_state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProductType',
            fields=[
                ('spt_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='耳机售卖类型编号')),
                ('spt_name', models.CharField(max_length=200, verbose_name='耳机售卖类型名称')),
                ('spt_use', models.CharField(max_length=255, verbose_name='使用方式')),
                ('spt_jack', models.CharField(max_length=255, verbose_name='插口类型')),
                ('spt_brand', models.CharField(max_length=255, verbose_name='品牌')),
                ('spt_length', models.CharField(max_length=255, verbose_name='线长')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('u_name', models.CharField(max_length=20, verbose_name='名字')),
                ('u_phone', models.CharField(max_length=30, verbose_name='电话')),
                ('u_email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('u_address', models.CharField(max_length=200, verbose_name='地址')),
                ('u_login_name', models.CharField(max_length=20, verbose_name='登录名')),
                ('u_login_password', models.CharField(max_length=100, verbose_name='登录密码')),
                ('u_balance', models.CharField(max_length=20, verbose_name='账户余额')),
                ('u_pay_password', models.CharField(max_length=100, verbose_name='支付密码')),
                ('u_state', models.CharField(max_length=2, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品编号')),
                ('p_imgs', models.CharField(max_length=255, verbose_name='图片')),
                ('p_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('p_cost_price', models.FloatField(max_length=10, verbose_name='商品成本价格')),
                ('p_sale_prict', models.FloatField(max_length=10, verbose_name='商品售卖价格')),
                ('p_postage', models.IntegerField(max_length=10, verbose_name='邮费')),
                ('p_sku', models.IntegerField(max_length=20, verbose_name='库存')),
                ('p_size', models.CharField(max_length=200, verbose_name='商品尺寸')),
                ('p_hot', models.CharField(max_length=2, verbose_name='是否热卖')),
                ('p_recommend', models.CharField(max_length=2, verbose_name='是否推荐')),
                ('p_state', models.CharField(max_length=2, verbose_name='状态')),
                ('p_up_down', models.CharField(max_length=2, verbose_name='上/下架')),
                ('pt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.producttype', verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('o_count', models.IntegerField(max_length=10, verbose_name='购买数量')),
                ('o_price', models.FloatField(max_length=20, verbose_name='购买价格')),
                ('o_address', models.CharField(max_length=50, verbose_name='邮购地址')),
                ('o_receiver', models.CharField(max_length=50, verbose_name='收货人')),
                ('o_phone', models.CharField(max_length=50, verbose_name='电话')),
                ('o_state', models.CharField(max_length=2, verbose_name='状态')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.product', verbose_name='关联商品')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.user', verbose_name='关联用户')),
            ],
        ),
        migrations.CreateModel(
            name='Middle',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='中间表编号')),
                ('m_use', models.CharField(max_length=255, verbose_name='使用方式')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.product', verbose_name='商品编号')),
                ('spt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.saleproducttype', verbose_name='售卖类型编号')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('c_content', models.CharField(blank=True, max_length=200, verbose_name='评论内容')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('c_state', models.CharField(max_length=2, verbose_name='状态')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.product', verbose_name='关联商品')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.user', verbose_name='关联用户')),
            ],
        ),
    ]
