# Generated by Django 3.1.2 on 2021-03-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cid', models.CharField(max_length=255,primary_key=True, serialize=False, verbose_name='购物车id')),
                ('price', models.FloatField(max_length=20, verbose_name='购买价格')),
                ('count', models.IntegerField(max_length=10, verbose_name='购买数量')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.product', verbose_name='关联商品')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.user', verbose_name='关联用户')),
            ],
        ),
    ]
